### ISSUE TITLE
1.16.3 stable- with pet ai(petai_v1.3.4.zip) and feverstonehorse(FeverstoneHorses-v1.2.4-1.16.x)-Sound and petai error

### ISSUE THREAD

**Issue by Aledark789** [Ahrondus/VS_Horse#10]
reported this to gerste on the modb also since it might be linked to his mod too.
Thanks for the mod, been a dream of mine since sooo many years :)

-----------------------------
Sounds warnings/errors from client-main.txt

13.2.2022 02:36:05 [Warning] Audio File not found: feverstonehorses:sounds/creatures/horse/horsedamage.ogg
13.2.2022 02:36:59 [Warning] Audio File not found: feverstonehorses:sounds/creatures/horse/neigh.ogg
----------------------
server-main.txt
13.2.2022 02:26:08 [Error] Error thrown trying to serialize entity with code feverstonehorses:horse-female, will not save, sorry! Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PetAI.EntityPet.getInventoryTree()
   at PetAI.EntityPet.ToBytes(BinaryWriter writer, Boolean forClient)
   at Vintagestory.Server.ServerChunk.BeforeSerialization()

-------------------------
When i tryed to kill 1 horse and skin it.

13.2.2022 02:36:16 [Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(_EWaCktsS2JyUbMhFd5RdMtCiCZOA packet, ConnectedClient client)
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)
13.2.2022 02:36:21 [Error] Error thrown trying to serialize entity with code feverstonehorses:horse-male, will not save, sorry! Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PetAI.EntityPet.getInventoryTree()
   at PetAI.EntityPet.ToBytes(BinaryWriter writer, Boolean forClient)
   at Vintagestory.Server.ServerChunk.BeforeSerialization()
13.2.2022 02:37:12 [Warning] Server overloaded. A tick took 771ms to complete.

---------------
Feedback: 
Possibility to have a view mode that the horse head is less in the way? Just wondering. Hard to place block or dig...also i can hurt my own horse if i misclick while im on top of him.

Config to tweak the horse spawning conditions(max per chunk, chances etc...i know it can be done with a json patching tough...but might be good if you choose to do so :) On single player if you do /entity countg there was 60 hares 30 horses 10 sheep 10 pigs as reference. Usually hare win by much wider margin. I think it should be toned down a bit (but it's just my take on it).

**Comment by G3rste** [comment]
The file of the female horse contains too many harvestable keywords in the server behaviors.
This most likely causes the crashing when skinning:
![image](https://user-images.githubusercontent.com/66719048/153767502-09982334-3f71-4dc2-959a-0ac467e05404.png)

**Comment by Ahrondus** [comment]
Final Comment: Audio file paths updated, and duplicate behaviors removed. Cleaned up code for readability.
