### ISSUE TITLE
1.16.4 Stable with v1.3.6 petAI and v1.2.6 feverstonehorses :Porting with a TL/TP while on a horse will make the user crash and or forced to restart their game.

### ISSUE THREAD

**Issue by Aledark789** [Ahrondus/VS_Horse#21]
1.16.4 Stable with v1.3.6 petAI and v1.2.6 feverstonehorses :Porting with a TL/TP while on a horse will make the user crash and or forced to restart their game(problem loading the chunks on other side...ppl describe being stuck in some type of void).

**Comment by Aledark789** [comment]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: aurafurytweaks@0.0.3, bettercrates@1.4.1, extrachests@1.5.2, specializedbags-10Slot@0.4.1, tradeomat@1.6.0, game@1.16.4, carrycapacity@0.6.5, farmlanddropssoil@1.4.0, hudclock@2.7.0, medievalexpansion@3.7.1, petai@1.3.6, creative@1.16.4, survival@1.16.4, workbenchexpansion@1.4.1, bricklayers@0.8.2, feverstonehorses@1.2.6
3/12/2022 2:50:49 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.DidMount(EntityAgent entityAgent)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.FromBytes(BinaryReader stream)
   at Vintagestory.API.Common.Entities.Entity.FromBytes(BinaryReader reader, Boolean fromServer)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientChunk.LoadEntitiesFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j[] entities, Int32 entitiesCount, ClientMain game)
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_rRUf25tOqmvtcmyjeOruY6FKLsb p, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass102_0.<LoadChunkFromPacket>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/10/2022 10:18:57 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.4.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 5508

Start Time: 01d83491cc5f8868

Termination Time: 8

Application Path: G:\Program Files (x86)\Vintage Story\Vintagestory\Vintagestory.exe

Report Id: bb65cd8e-93bd-46b5-8b6e-3d33ca1e2b9f

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 3/10/2022 10:18:55 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2285548539015043790, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: efd0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0A6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0D6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0D5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0F5.tmp.txt
\\?\C:\Users\kepon\AppData\Local\Temp\WERD8D6.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_88c9e501cedc0e86c3e67567f884da0afebba2c_81245bb0_a30fcdcf-a065-4bbe-a787-c0ef6dbca550

Analysis symbol: 
Rechecking for solution: 0
Report Id: bb65cd8e-93bd-46b5-8b6e-3d33ca1e2b9f
Report Status: 268435456
Hashed bucket: 23f51d409fac8b4f6fb7e64970e79ace
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/9/2022 12:18:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141682226387760473, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: KERNELBASE.dll
P5: 10.0.19041.1503
P6: b2acaea9
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3498.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3881.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER38A2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER38B1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER38D1.tmp.txt
\\?\C:\Users\kepon\AppData\Local\Temp\WER399E.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_98611364a47f18c248c2e50b397bdb8519d631f_81245bb0_df187d62-63ed-461d-abd2-befd5234f1cd

Analysis symbol: 
Rechecking for solution: 0
Report Id: ab08ad4a-6ed2-4af2-a764-43ae63cef653
Report Status: 268435456
Hashed bucket: 3bf1c759099196e97db8c8a3459c3559
Cab Guid: 0 }

**Comment by Ahrondus** [comment]
I'm assuming this directly relates to the code with TLs. 
1.Assuming the TL only covers a specific area, or that the TL teleports an entity to a specific XYZ coordinate, it would cause a conflict by trying to teleport two entities to the exact same spot at the exact same time.
2. Or if the TL only covers the entity that is standing on the base, then the TL would teleport the horse, and since the player location is supposed to be tied to the horse but the horse now disappeared, it causes an error.

I'm not sure how to fix this directly, but can look into the code for the TLs.

**Comment by Konfuz** [comment]
In my case the game doesn't crash on teleport, instead all loaded chunks get invisible until I dismount the horse. I will still be on the origin-TL My suspicion: Only the horse enters the teleporter while the player-entity is not in the spot (hovering above the horse) the horse gets teleported and then immediately pulled back to the player as its attached to the actor(?).  

Horse also became non-interactible for a short while in one case. 

Dismounting the horse on TL letting it port alone, then following through and remounting works.
